export interface Product {
  id: string;
  name: string;
  price: string;
  image: string;
  images: string[];
  size: string;
  screenSize: string;
  resolution: string;
  tier: "PRO" | "PRIME" | "MAX" | "GT";
  features: string[];
  apps: string[];
  description?: string;
}

const githubBase = "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images";

export const products: Product[] = [
  {
    id: "ort32-pro",
    name: "ORT32 PRO",
    price: "₹15,999",
    image: `${githubBase}/AnyConv.com__32inch1.webp`,
    images: [
      `${githubBase}/AnyConv.com__32inch1.webp`,
      `${githubBase}/AnyConv.com__32lifestyle1.webp`,
      `${githubBase}/AnyConv.com__32inchmeasure.webp`,
      `${githubBase}/AnyConv.com__specification1.webp`,
      `${githubBase}/AnyConv.com__specification2.webp`,
      `${githubBase}/AnyConv.com__insidethebox.webp`,
    ],
    size: "32",
    screenSize: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "PRO",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
      "HD",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort32-prime",
    name: "ORT32 PRIME",
    price: "₹16,999",
    image: `${githubBase}/AnyConv.com__32inch2.webp`,
    images: [
      `${githubBase}/AnyConv.com__32inch2.webp`,
      `${githubBase}/AnyConv.com__32lifestyle2.webp`,
      `${githubBase}/AnyConv.com__32inchmeasure.webp`,
      `${githubBase}/AnyConv.com__specification1.webp`,
      `${githubBase}/AnyConv.com__specification2.webp`,
      `${githubBase}/AnyConv.com__insidethebox.webp`,
    ],
    size: "32",
    screenSize: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "PRIME",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
      "HD",
      "Free Live Channels & Cloud Operating System",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort32-max",
    name: "ORT32 MAX",
    price: "₹18,999",
    image: `${githubBase}/AnyConv.com__32inch3.webp`,
    images: [
      `${githubBase}/AnyConv.com__32inch3.webp`,
      `${githubBase}/AnyConv.com__32lifestyle3.webp`,
      `${githubBase}/AnyConv.com__32inchmeasure.webp`,
      `${githubBase}/AnyConv.com__specification1.webp`,
      `${githubBase}/AnyConv.com__specification2.webp`,
      `${githubBase}/AnyConv.com__insidethebox.webp`,
    ],
    size: "32",
    screenSize: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "MAX",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
      "HD",
      "BT Remote with Voice Assistant",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort32-gt",
    name: "ORT32 GT",
    price: "₹20,999",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__32inch4.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__32inch4.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__32lifestyle4.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__32inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "32",
    screenSize: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "GT",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
      "HD",
      "BT Remote with Voice Assistant",
    ],
    apps: [
      "Google Play",
      "Google TV",
      "Netflix",
      "Prime Video",
      "YouTube",
      "Sony Liv",
      "Dolby Audio",
    ],
  },
  {
    id: "ort43-pro",
    name: "ORT43 PRO",
    price: "₹30,990",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch1.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43lifestyle2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "43",
    screenSize: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "PRO",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "FHD",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort43-prime",
    name: "ORT43 PRIME",
    price: "₹31,990",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch2.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43lifestyle2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "43",
    screenSize: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "PRIME",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "FHD",
      "Free Live Channels & Cloud Operating System",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort43-max",
    name: "ORT43 MAX",
    price: "₹33,990",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch3.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch3.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43lifestyle3.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "43",
    screenSize: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "MAX",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "FHD",
      "BT Remote with Voice Assistant",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort43-gt",
    name: "ORT43 GT",
    price: "₹35,990",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch4.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inch4.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43lifestyle4.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__43inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "43",
    screenSize: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "GT",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "FHD",
      "BT Remote with Voice Assistant",
    ],
    apps: [
      "Google Play",
      "Google TV",
      "Netflix",
      "Prime Video",
      "YouTube",
      "Sony Liv",
      "Dolby Audio",
    ],
  },
  {
    id: "ort55-max",
    name: "ORT55 MAX",
    price: "₹55,999",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55inch1.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55inch1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55lifestyle1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "55",
    screenSize: '140cm (55")',
    resolution: "4K UHD HDR 10",
    tier: "MAX",
    features: [
      "App Support",
      "Built in Wi-Fi & BT",
      "Frameless Design",
      "Wall Mountable",
      "Dual Band Wi-Fi",
      "A+ Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort55-gt",
    name: "ORT55 GT",
    price: "₹58,999",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55inch2.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55inch2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55lifestyle2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__55inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "55",
    screenSize: '140cm (55")',
    resolution: "4K UHD HDR 10",
    tier: "GT",
    features: [
      "App Support",
      "Built in Wi-Fi & BT",
      "Frameless Design",
      "Wall Mountable",
      "Dual Band Wi-Fi",
      "A+ Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
    apps: [
      "Google Play",
      "Google TV",
      "Netflix",
      "Prime Video",
      "YouTube",
      "Sony Liv",
      "Dolby Audio",
    ],
  },
  {
    id: "ort65-max",
    name: "ORT65 MAX",
    price: "₹65,999",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65inch1.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65inch1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65lifestyle1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "65",
    screenSize: '165cm (65")',
    resolution: "4K UHD HDR 10",
    tier: "MAX",
    features: [
      "App Support",
      "Built in Wi-Fi & BT",
      "Frameless Design",
      "Wall Mountable",
      "Dual Band Wi-Fi",
      "A+ Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
    apps: ["Netflix", "Prime Video", "YouTube", "Sony Liv", "Dolby Audio"],
  },
  {
    id: "ort65-gt",
    name: "ORT65 GT",
    price: "₹68,999",
    image: "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65inch2.webp",
    images: [
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65inch2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65lifestyle2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__65inchmeasure.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification1.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__specification2.webp",
      "https://raw.githubusercontent.com/sahil00000001/ORIZMA/refs/heads/main/attached_assets/New_Images/AnyConv.com__insidethebox.webp",
    ],
    size: "65",
    screenSize: '165cm (65")',
    resolution: "4K UHD HDR 10",
    tier: "GT",
    features: [
      "App Support",
      "Built in Wi-Fi & BT",
      "Frameless Design",
      "Wall Mountable",
      "Dual Band Wi-Fi",
      "A+ Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
    apps: [
      "Google Play",
      "Google TV",
      "Netflix",
      "Prime Video",
      "YouTube",
      "Sony Liv",
      "Dolby Audio",
    ],
  },
];
