import { db } from "./db";
import { products } from "@shared/schema";

const productData = [
  {
    id: "ort32-pro",
    name: "ORT32 PRO",
    price: "₹15,999",
    image: "/attached_assets/generated_images/32-inch_TV_product_shot_6cb4aeaf.png",
    size: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "PRO",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
    ],
  },
  {
    id: "ort32-prime",
    name: "ORT32 PRIME",
    price: "₹16,999",
    image: "/attached_assets/generated_images/32-inch_TV_product_shot_6cb4aeaf.png",
    size: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "PRIME",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
      "Free Live Channels & Cloud Operating System",
    ],
  },
  {
    id: "ort32-max",
    name: "ORT32 MAX",
    price: "₹18,999",
    image: "/attached_assets/generated_images/32-inch_TV_product_shot_6cb4aeaf.png",
    size: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "MAX",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
  },
  {
    id: "ort32-gt",
    name: "ORT32 GT",
    price: "₹20,999",
    image: "/attached_assets/generated_images/32-inch_TV_product_shot_6cb4aeaf.png",
    size: '80cm (32")',
    resolution: "1366 X 768 HD",
    tier: "GT",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Bezel less design",
      "A Grade Display Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
      "Google Play",
      "Google TV",
    ],
  },
  {
    id: "ort43-pro",
    name: "ORT43 PRO",
    price: "₹30,990",
    image: "/attached_assets/generated_images/43-inch_TV_product_shot_758a16b4.png",
    size: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "PRO",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
    ],
  },
  {
    id: "ort43-prime",
    name: "ORT43 PRIME",
    price: "₹31,990",
    image: "/attached_assets/generated_images/43-inch_TV_product_shot_758a16b4.png",
    size: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "PRIME",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "Free Live Channels & Cloud Operating System",
    ],
  },
  {
    id: "ort43-max",
    name: "ORT43 MAX",
    price: "₹33,990",
    image: "/attached_assets/generated_images/43-inch_TV_product_shot_758a16b4.png",
    size: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "MAX",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
  },
  {
    id: "ort43-gt",
    name: "ORT43 GT",
    price: "₹35,990",
    image: "/attached_assets/generated_images/43-inch_TV_product_shot_758a16b4.png",
    size: '109cm (43")',
    resolution: "1920 X 1080 FHD",
    tier: "GT",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
      "Google Play",
      "4K UHD HDR 10",
    ],
  },
  {
    id: "ort55-pro",
    name: "ORT55 PRO",
    price: "₹55,990",
    image: "/attached_assets/generated_images/55-inch_TV_product_shot_ff8031e3.png",
    size: '140cm (55")',
    resolution: "3840 X 2160 4K UHD",
    tier: "PRO",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
    ],
  },
  {
    id: "ort55-prime",
    name: "ORT55 PRIME",
    price: "₹56,990",
    image: "/attached_assets/generated_images/55-inch_TV_product_shot_ff8031e3.png",
    size: '140cm (55")',
    resolution: "3840 X 2160 4K UHD",
    tier: "PRIME",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "Free Live Channels & Cloud Operating System",
    ],
  },
  {
    id: "ort55-max",
    name: "ORT55 MAX",
    price: "₹58,990",
    image: "/attached_assets/generated_images/55-inch_TV_product_shot_ff8031e3.png",
    size: '140cm (55")',
    resolution: "3840 X 2160 4K UHD",
    tier: "MAX",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
  },
  {
    id: "ort55-gt",
    name: "ORT55 GT",
    price: "₹60,990",
    image: "/attached_assets/generated_images/55-inch_TV_product_shot_ff8031e3.png",
    size: '140cm (55")',
    resolution: "3840 X 2160 4K UHD",
    tier: "GT",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
      "Google Play",
      "4K UHD HDR 10",
    ],
  },
  {
    id: "ort65-pro",
    name: "ORT65 PRO",
    price: "₹75,990",
    image: "/attached_assets/generated_images/65-inch_TV_product_shot_7baf4268.png",
    size: '164cm (65")',
    resolution: "3840 X 2160 4K UHD",
    tier: "PRO",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
    ],
  },
  {
    id: "ort65-prime",
    name: "ORT65 PRIME",
    price: "₹76,990",
    image: "/attached_assets/generated_images/65-inch_TV_product_shot_7baf4268.png",
    size: '164cm (65")',
    resolution: "3840 X 2160 4K UHD",
    tier: "PRIME",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "Free Live Channels & Cloud Operating System",
    ],
  },
  {
    id: "ort65-max",
    name: "ORT65 MAX",
    price: "₹78,990",
    image: "/attached_assets/generated_images/65-inch_TV_product_shot_7baf4268.png",
    size: '164cm (65")',
    resolution: "3840 X 2160 4K UHD",
    tier: "MAX",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
    ],
  },
  {
    id: "ort65-gt",
    name: "ORT65 GT",
    price: "₹80,990",
    image: "/attached_assets/generated_images/65-inch_TV_product_shot_7baf4268.png",
    size: '164cm (65")',
    resolution: "3840 X 2160 4K UHD",
    tier: "GT",
    features: [
      "Built in Wi-Fi",
      "Remote Control",
      "Wall Mountable",
      "Frameless Design",
      "A Grade Display Panel/Glossy Panel",
      "Ultrabright Display",
      "BT Remote with Voice Assistant",
      "Google Play",
      "4K UHD HDR 10",
    ],
  },
];

async function seed() {
  console.log("Seeding database...");
  
  // Clear existing products
  await db.delete(products);
  
  // Insert product data
  await db.insert(products).values(productData);
  
  console.log("Database seeded successfully!");
  console.log(`Inserted ${productData.length} products`);
  process.exit(0);
}

seed().catch((error) => {
  console.error("Error seeding database:", error);
  process.exit(1);
});
